name: Automating

on:
  schedule:
    - cron: '0 18 * * *'  # Run daily at midnight

jobs:
  cron_job:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Running script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_TRACKS }}
          key: ${{ secrets.SSH_KEY_TRACKS }}
          username: ${{ secrets.SERVER_USERNAME_TRACKS }}
          script: cd ${{ secrets.PROJECT_PATH_TRACKS }} && git pull origin master && npm install && node index.js


